services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - /share/Container/changedetection-data:/datastore
    env_file:
      - /env/common.env
    environment:
      - WEBDRIVER_URL=http://browser-chrome:4444/wd/hub
    ports:
      - 5000:5000
    restart: unless-stopped
  browser-chrome:
    hostname: browser-chrome
    image: selenium/standalone-chrome:4
    environment:
        - VNC_NO_PASSWORD=1
        - SCREEN_WIDTH=1920
        - SCREEN_HEIGHT=1080
        - SCREEN_DEPTH=24
    volumes:
        # Workaround to avoid the browser crashing inside a docker container
        # See https://github.com/SeleniumHQ/docker-selenium#quick-start
        - /dev/shm:/dev/shm
    restart: unless-stopped

