---
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    env_file:
      - /env/common.env
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /share/Container/homeassistant:/config
    ports:
      - 8123:8123
    restart: unless-stopped