version: '3.8'
services:
  swag:
    image: lscr.io/linuxserver/swag
    env_file:
      - /env/common.env
      - /env/swag.env
    environment:
      - URL=${URL}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    networks:
      apps: {}
    volumes:
      - /share/Container/swag:/config
    ports:
      - "443:443"

networks:
  apps:
    external: true
