services:
  postgres:
    image: postgres:16-alpine
    env_file:
    - /env/linkwarden.env
    restart: always
    volumes:
      - /share/Container/linkwarden/data/pgdata:/var/lib/postgresql/data
  linkwarden:
    env_file:
    - /env/linkwarden.env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    image: ghcr.io/linkwarden/linkwarden:latest
    ports:
      - 3000:3000
    volumes:
      - /share/Container/linkwarden/data:/data/data
    depends_on:
      - postgres
      - meilisearch
  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    restart: always
    env_file:
    - /env/linkwarden.env
    volumes:
      - /share/Container/linkwarden/meili_data:/meili_data
