version: '3.8'

services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: tailscale
    env_file:
      - /env/tailscale.env
    environment:
      - TS_EXTRA_ARGS=--advertise-exit-node
      - TS_ADVERTISE_ROUTES=0.0.0.0/0
      - TS_AUTH_ONCE=true
      - TS_HOSTNAME=qnap
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    privileged: true